# Generated by Django 5.2.4 on 2025-08-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genders', '0001_initial'),
        ('location', '0001_initial'),
        ('tattoo_body_parts', '0001_initial'),
        ('tattoo_machine_types', '0001_initial'),
        ('tattoo_product_brands', '0001_initial'),
        ('tattoo_styles', '0001_initial'),
        ('tattoo_techniques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('artistic_name', models.CharField(max_length=30, unique=True, verbose_name='Nome artístico')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('started_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano que começou a tatuar')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artist_photos/', verbose_name='Foto de perfil')),
                ('is_apprentice', models.BooleanField(default=False, verbose_name='Aprendiz ou Iniciante')),
                ('only_women', models.BooleanField(default=False, verbose_name='Atende apenas mulheres')),
                ('safe_space', models.BooleanField(default=False, verbose_name='Espaço seguro')),
                ('tattoos_private_parts', models.BooleanField(default=False, verbose_name='Tatua partes íntimas')),
                ('uses_vegan_products', models.BooleanField(default=False, verbose_name='Utiliza produtos veganos')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone comercial')),
                ('watermark_tag', models.ImageField(blank=True, null=True, upload_to='watermarks/', verbose_name="Tag/marca d'água")),
                ('atende_em_outros_paises', models.BooleanField(default=False, verbose_name='Atende em outros países')),
                ('atende_em_outros_estados', models.BooleanField(default=False, verbose_name='Atende em outros estados')),
                ('atende_em_outras_cidades', models.BooleanField(default=False, verbose_name='Atende em outras cidades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_parts_not_tattooed', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='tattoo_body_parts.tattoobodypart', verbose_name='Partes do corpo que não tatua')),
                ('cidades_que_atende', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='location.cidade', verbose_name='Cidades onde atende')),
                ('estados_que_atende', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='location.estado', verbose_name='Estados onde atende')),
                ('favorite_styles', models.ManyToManyField(blank=True, related_name='preferred_by_artists', to='tattoo_styles.tattoostyle', verbose_name='Estilos preferidos')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tattoo_artists', to='genders.gender', verbose_name='Gênero')),
                ('machine_types', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='tattoo_machine_types.tattoomachinetype', verbose_name='Tipos de máquina que utiliza')),
                ('paises_que_atende', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='location.pais', verbose_name='Países onde atende')),
                ('product_brands', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='tattoo_product_brands.tattooproductbrand', verbose_name='Marcas de produtos utilizados')),
                ('styles', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='tattoo_styles.tattoostyle', verbose_name='Estilos')),
                ('techniques', models.ManyToManyField(blank=True, related_name='tattoo_artists', to='tattoo_techniques.tattootechnique', verbose_name='Técnicas')),
            ],
            options={
                'verbose_name': 'Tatuador',
                'verbose_name_plural': 'Tatuadores',
                'db_table': 'tattoo_artist',
            },
        ),
    ]
