# Generated by Django 5.2.4 on 2025-08-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('tattoo_artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='tattoo_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tattoo_artist.tattooartist'),
        ),
    ]
