# Generated by Django 5.2.4 on 2025-08-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do estilo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do estilo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estilo de Tatuagem',
                'verbose_name_plural': 'Estilos de Tatuagem',
                'db_table': 'tattoo_styles',
            },
        ),
    ]
