# Generated by Django 5.2.4 on 2025-08-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tattoo_artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/', verbose_name='Imagem da Arte')),
                ('type', models.CharField(choices=[('portfolio', 'Portfólio'), ('available', 'Arte Disponível'), ('interested', 'Deseja Tatuar')], max_length=20, verbose_name='Tipo da Arte')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (opcional)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tattoo_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='tattoo_artist.tattooartist')),
            ],
            options={
                'verbose_name': 'Arte de Tatuagem',
                'verbose_name_plural': 'Artes de Tatuagem',
                'db_table': 'tattoo_artworks',
            },
        ),
    ]
